/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurfaces;

import aControl.XxXx01Control;
import static aGlobal.XxXx00Global.*;
import java.awt.Dimension;
import java.awt.event.KeyEvent;

/**
 *
 * @author b6dmin
 */
public class XxXx01GetUserPanel extends javax.swing.JPanel {

    private XxXx01Control c;

    public void setControl(XxXx01Control c) {
        this.c = c;
    }

    public void setup() {
        System.out.println("XxXxLoginPanel: "
                + this.getWidth() + "x" + this.getHeight());
        lblUser.setText(LABEL_USER_TXT);
        if (TEST_MODE) {
            txtUser.setText(TEST_USERNAME);
        } else {
            txtUser.setText(TEXTFIELD_TXT);
        }
        btnLogin.setText(BUTTON_LOGIN_TXT);
    }

    public void txtUserRequestFocus() {
        txtUser.requestFocus();
    }

    /**
     * Creates new form XxXxLoginPanel
     */
    public XxXx01GetUserPanel() {
        System.out.println("<XxXxLoginPanel>");
        initComponents();
        super.setPreferredSize(new Dimension(GRAPHITY_WIDTH, GRAPHITY_HEIGHT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.GridBagLayout());

        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUser.setText("lblUser");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(lblUser, gridBagConstraints);

        txtUser.setText("txtUser");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 6.0;
        add(txtUser, gridBagConstraints);

        btnLogin.setText("btnLogin");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(btnLogin, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        c.userName(txtUser.getText());
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            c.userName(txtUser.getText());
        }
    }//GEN-LAST:event_btnLoginKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
