/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurfaces;

import aControl.XxXx01Control;
import static aGlobal.XxXx00Global.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author b6dmin
 */
public class XxXx01LoginPanel extends javax.swing.JPanel {

    private XxXx01Control c;

    public void setControl(XxXx01Control c) {
        this.c = c;
    }

    public void setup() {
        System.out.println("XxXxLoginPanel: "
                + this.getWidth() + "x" + this.getHeight());
        lblPassword.setText(LABEL_PSWD_TXT);
        if (TEST_MODE) {
            txtPassword.setText(TEST_USERPSWD);
        } else {
            txtPassword.setText(PASSWORD_TXT);
        }
        btnSubmit.setText(BUTTON_SUBMIT_TXT);
    }

    public void txtPswdRequestFocus() {
        txtPassword.requestFocus();
    }

    /**
     * Creates new form XxXxLoginPanel
     */
    public XxXx01LoginPanel() {
        System.out.println("<XxXxLoginPanel>");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.GridBagLayout());

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword.setText("lblPassword");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(lblPassword, gridBagConstraints);

        txtPassword.setText("txtPassword");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 6.0;
        add(txtPassword, gridBagConstraints);

        btnSubmit.setText("btnSubmit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        btnSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSubmitKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(btnSubmit, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        c.userPassword(txtPassword.getText());
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSubmitKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            c.userPassword(txtPassword.getText());
        }
    }//GEN-LAST:event_btnSubmitKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
